### ISSUE TITLE
Pods of annotated deployment not starting

### ISSUE THREAD

**Issue by henrikengelbrink** [hashicorp/vault-k8s#101]
Hi everyone,

I'm currently trying to use the Vault k8s Injector to inject a secret automatically from Vault into my deployment. Unfortunately it's not working. I'm using the following deployment.yml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-app
  namespace: vault
  labels:
    app: vault-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-app
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: 'mqtt-server-cert-secret-role'
        vault.hashicorp.com/agent-inject-secret-foo: "kv/data/mqtt-server-cert"
      labels:
        app: vault-app
    spec:
      serviceAccountName: vault-auth
      containers:
        - name: vault-app
          image: tutum/hello-world:latest
          ports:
            - containerPort: 80
```

If I apply this yaml, `describe deploy vault-app -n vault` gives me the following output:
```
Name:                   vault-app
Namespace:              vault
CreationTimestamp:      Thu, 05 Mar 2020 14:45:44 +0100
Labels:                 app=vault-app
Annotations:            deployment.kubernetes.io/revision: 1
                        kubectl.kubernetes.io/last-applied-configuration:
                          {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"vault-app"},"name":"vault-app","namespace":"vaul...
Selector:               app=vault-app
Replicas:               1 desired | 0 updated | 0 total | 0 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=vault-app
  Annotations:      vault.hashicorp.com/agent-inject: true
                    vault.hashicorp.com/agent-inject-secret-foo: kv/data/mqtt-server-cert
                    vault.hashicorp.com/role: mqtt-server-cert-secret-role
  Service Account:  vault-auth
  Containers:
   vault-app:
    Image:        tutum/hello-world:latest
    Port:         80/TCP
    Host Port:    0/TCP
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type             Status  Reason
  ----             ------  ------
  Progressing      True    NewReplicaSetCreated
  Available        False   MinimumReplicasUnavailable
  ReplicaFailure   True    FailedCreate
OldReplicaSets:    <none>
NewReplicaSet:     vault-app-7d766f797f (0/1 replicas created)
Events:
  Type    Reason             Age    From                   Message
  ----    ------             ----   ----                   -------
  Normal  ScalingReplicaSet  4m12s  deployment-controller  Scaled up replica set vault-app-7d766f797f to 1
```

I have no idea where the problem can be. I also looked into the logs of vault and the vault-injector, but there is nothing related to this.

I'm not 100% sure whether enabling k8s for vault was successfull, is there any possibilty to check this ?

Does anyone have an idea what could be the problem ?
