### ISSUE TITLE
Vault Injector not writing data to secrets [v1.3.3]

### ISSUE THREAD

**Issue by Ares3266** [hashicorp/vault-k8s#117]
The vault agent injector writes the files to the shared volume, but does not actually write any data to the files.

Running on GKE with the consul backend. Version 1.3.3

TLS is set to disable as this is just a rapid prototype.

# Deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vt-notifications-collector
  labels:
    project: phoenix
    app: vt-notification-collector
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vt-notification-collector
  template:
    metadata:
      name: vt-notification-collector
      labels:
        project: phoenix
        app: vt-notification-collector
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-vt-key.json: phoenix/collector/vt-key
        vault.hashicorp.com/agent-inject-secret-synapse-key.json: phoenix/collector/synapse-key
        vault.hashicorp.com/agent-inject-secret-gcloud.json: phoenix/google/gcloud
        vault.hashicorp.com/role: 'phoenix-collector'
        vault.hashicorp.com/log-level: 'debug'
    spec:
      serviceAccountName: vault-auth
      containers:
        - image: registry.gitlab.com/cto-uk/phoenix/collector:<VERSION>
          name: collector
          env:
            - name: CONSUL_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NAMESPACE
              value: phoenix
      imagePullSecrets:
        - name: "cto-uk-registry"
```

# Log Files

[injector-logs.txt](https://github.com/hashicorp/vault-k8s/files/4439035/injector-logs.txt)
[server-logs.txt](https://github.com/hashicorp/vault-k8s/files/4439036/server-logs.txt)
[agent-logs.txt](https://github.com/hashicorp/vault-k8s/files/4439037/agent-logs.txt)
[app-logs.txt](https://github.com/hashicorp/vault-k8s/files/4439038/app-logs.txt)
