### ISSUE TITLE
Run as user is not working

### ISSUE THREAD

**Issue by elnoxgdl** [hashicorp/vault-k8s#135]
Hi All,

I have the following annotations setup for my deployment.

```yaml
vault.hashicorp.com/agent-inject: "true"
vault.hashicorp.com/agent-inject-status: "update"
vault.hashicorp.com/agent-run-as-user: "0"
vault.hashicorp.com/agent-run-as-group: "0"
vault.hashicorp.com/agent-inject-secret-.env: "secret/data/superduper/.env"
vault.hashicorp.com/agent-inject-template-.env: |-
  {{`{{ with secret "secret/data/superduper/.env" }}
  {{- range $k, $v := .Data.data }}
  {{ $k }}={{ $v }}
  {{- end }}
  {{ end }}`}}
vault.hashicorp.com/agent-inject-command-.env: "/bin/sh -c 'touch /tmp/renew.txt; whoami; id;'"
vault.hashicorp.com/log-level: "trace"
vault.hashicorp.com/role: {{ .Values.vault.role.staging | quote }}
```

When i log into the container to see how the agent was started up its not using uid 0 nor gid 0.
I'm using the vault helm chart to deploy the injector, didn't work. I used the vault-k8s deploy manifests and that ALSO DID NOT work. I'm setting the following environment variables.

```yaml
      containers:
        - name: sidecar-injector
          image: "hashicorp/vault-k8s:0.3.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: AGENT_INJECT_LISTEN
              value: ":8080"
            - name: AGENT_INJECT_LOG_LEVEL
              value: "debug"
            - name: AGENT_INJECT_LOG_FORMAT
              value: "standard"
            - name: AGENT_INJECT_VAULT_ADDR
              value: "https://vault.mydomain.net:8200"
            - name: AGENT_INJECT_VAULT_IMAGE
              value: "vault:1.4.1"
            - name: AGENT_INJECT_TLS_AUTO
              value: vault-agent-injector-cfg
            - name: AGENT_INJECT_TLS_AUTO_HOSTS
              value: "vault-agent-injector-svc,vault-agent-injector-svc.$(NAMESPACE),vault-agent-injector-svc.$(NAMESPACE).svc"
            - name: AGENT_INJECT_RUN_AS_USER
              value: "0"
            - name: AGENT_INJECT_RUN_AS_GROUP
              value: "0"
```

So i tought it might be my security context, which I forcefully set as below:
```yaml
securityContext:
  runAsUser: 0
  runAsGroup: 0
  runAsNonRoot: false
```

So no idea how to force it to run the vault side car agent  as root. I need this because I need to reload php-fpm that is also using root. So at this point is unknown to me how in the current 0.3.0 is this possible? I am running this in a K3S cluster.

Also the docker image for vault-k8s is the 0.3.0 but is being postfixed with -dev  so I'm wondering if the docker hub image is correct is not missing any feature?

```
/ $ /vault-k8s
Usage: vault-k8s [--version] [--help] <command> [<args>]

Available commands are:
    agent-inject    Vault Agent injector service
    version         Prints the version

/ $ /vault-k8s  version
vault-k8s 0.3.0-dev
```

Another issue as well is you clearly state you offer the binary but it seems your server https://releases.hashicorp.com is not showing up any vault-k8s binary at all, so I can't build the binary at all.
