### ISSUE TITLE
Bug : Annotation for resource request doesn't work. 

### ISSUE THREAD

**Issue by iusergii** [hashicorp/vault-k8s#144]
**Describe the bug**
According to Agent Annotations [Doc](https://www.vaultproject.io/docs/platform/k8s/injector/annotations#vault-hashicorp-com-agent-requests-cpu) I can overwrite Agent resource request with foloowing annotations
```
vault-hashicorp-com-agent-requests-cpu: 10m
vault-hashicorp-com-agent-requests-mem: 16Mi
```

**To Reproduce**
Add annotation to Deployment:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-agent
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-agent
  labels:
    app: vault-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-agent
  template:
    metadata:
      labels:
        app: vault-agent
        Product: DevOps
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "vault-agent-test"
        # AWS CREDS
        vault.hashicorp.com/agent-inject-secret-aws: aws/creds/s3
        vault-hashicorp-com-agent-requests-cpu: 10m
        vault-hashicorp-com-agent-requests-mem: 16Mi
    spec:
      serviceAccount: vault-agent
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```
Check that resource request wasn't changed:
```
kubectl get pods -l 'app=vault-agent' -o=jsonpath='{.items[0].spec.containers[*].resources.requests'

cpu:250m memory:64Mi
```

**Environment:**
Checked on v.0.3.0 and 0.4.0

**Additional context**
I guess that the default resource request is quite big for Agent.  And seems that `limits` works
