### ISSUE TITLE
Vault Agent Injector: vault-agent-init x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by logand22** [hashicorp/vault-k8s#151]
While attempting to use vault-agent-injector, I came across an x509 error while the init Container was running. I attempted initially to use the following annotations:

```
template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "devweb-app"
        vault.hashicorp.com/agent-inject-secret-credentials.txt: "secret/data/devwebapp/config"
        vault.hashicorp.com/tls-skip-verify: "true"
```
however I still received the x509 error. 

I exec'd into the container and examined `/tmp/config.json` and saw the following values:

```json
{
  "auto_auth": {
    "method": {
      "type": "kubernetes",
      "mount_path": "auth/kubernetes",
      "config": {
        "role": "devweb-app"
      }
    },
    "sink": [
      {
        "type": "file",
        "config": {
          "path": "/home/vault/.vault-token"
        }
      }
    ]
  },
  "exit_after_auth": true,
  "pid_file": "/home/vault/.pid",
  "vault": {
    "address": "https://vault.example.com",
    "tls_skip_verify": true
  },
  "template": [
    {
      "destination": "/vault/secrets/credentials.txt",
      "contents": "{{ with secret \"secret/data/devwebapp/config\" }}{{ range $k, $v := .Data }}{{ $k }}: {{ $v }}\n{{ end }}{{ end }}",
      "left_delimiter": "{{",
      "right_delimiter": "}}"
    }
  ]
}
```

helm version:
- version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}

chart version: 
- hashicorp/vault 0.6.0

kubernetes version:
- Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
- Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

I would expect not to receive the x509 error when using TLS Skip Verify. Is there something I am missing? Thanks
