### ISSUE TITLE
Add support for token only

### ISSUE THREAD

**Issue by jasonodonnell** [hashicorp/vault-k8s#16]
There are use cases where a valid token could be shared with other containers in the pod.  I think an annotation could be added to support this use case.

```yaml
vault.hashicorp.com/agent-inject: "true"
vault.hashicorp.com/agent-inject-token-only: "true"
vault.hashicorp.com/role: "myrole"
```
vs

```yaml
vault.hashicorp.com/agent-inject: "true"
vault.hashicorp.com/agent-inject-secret-token: "auth/token/lookup-self"
vault.hashicorp.com/agent-inject-template-token: |
    {{- with secret "auth/token/lookup-self" -}}
        {{.Data.id}}
     {{- end }}
 vault.hashicorp.com/role: "myrole"
```

**Comment by goffinf** [comment]
This is definitely a use case for us, and in particular for containerised CI agents that need access to Vault. The agent runs pipelines for arbitrary purposes and therefore the secrets that may be required cannot be predicted.

So that pattern we follow is the vault-agent runs as a sidecar to maintain the auth token (K8s Auth method) and that token is mounted into the ci container and thereby available to any pipelines running on on that agent.

**Comment by philippeboyd** [comment]
Same thing for us. I'm facing the problem where my app needs to access the Vault token itself (mounted in the agent's `/home/vault/.token`).

Is there any development on this issue? In the mean time, is there a "hacky" way to access that token from another conainer?

**Comment by jasonodonnell** [comment]
Hi @philippeboyd, you can simply use the annotation I stated above today:

```
vault.hashicorp.com/agent-inject: "true"
vault.hashicorp.com/agent-inject-secret-token: "auth/token/lookup-self"
vault.hashicorp.com/agent-inject-template-token: |
    {{- with secret "auth/token/lookup-self" -}}
        {{.Data.id}}
     {{- end }}
 vault.hashicorp.com/role: "myrole"
```

This feature would just automate that template.

**Comment by philippeboyd** [comment]
@jasonodonnell thanks a lot! Didn't think it would work... Though I had to adjust the template to be compatible with Helm charts. since delimiters `{{` and `}}` are used with Helm. The Vault delimiters `{{` and `}}` were in conflict and I was hitting the error `function "secret" not defined`.

Here's my adjusted solution (notice the backticks):

```yaml
vault.hashicorp.com/agent-inject: "true"
vault.hashicorp.com/agent-inject-secret-token: "auth/token/lookup-self"
vault.hashicorp.com/agent-inject-template-token: |
  {{`{{- with secret "auth/token/lookup-self" -}}
    {{.Data.id}}
  {{- end }}`}}
```

Cheers!
