### ISSUE TITLE
supports to kubernetes.io/dockerconfigjson

### ISSUE THREAD

**Issue by ch0mik** [hashicorp/vault-k8s#160]
this secret currently I stored into clean kubernetes, but I want to store it into Vault.

<pre>
apiVersion: v1
kind: Secret
metadata:
  name: repocredentials
  namespace: myns
data:
  .dockerconfigjson: ewo--cut--9Cgl9Cn0K
type: kubernetes.io/dockerconfigjson
</pre>

Is the possible store this type of secres into Vault ?

**Comment by vijaymhaske** [comment]
Hi @ch0mik -  I am also facing the same issue. Did you figured out how to achieve this?

**Comment by danielFlemstrom** [comment]
Anyone got it working?  
As I see it, the obvious way to do this should be the following (That does not work):

```
apiVersion: v1
kind: Secret
metadata:
  name: my-private-registry-pull-secret
  annotations:
    avp.kubernetes.io/path: "secret/data/myappsecrets"    # Vault Path
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: MY_KEY_TO_REPO_AUTH               # Treat contents in Vault as docker config.
```

This should be one of the first issues you encounter when starting out with k8 and vault so I guess we are approaching it from the wrong direction, or are people happy with storing their repo keys in GIT ?
