### ISSUE TITLE
Sidecar Overwrites Secrets Generated By Init Container

### ISSUE THREAD

**Issue by borchero** [hashicorp/vault-k8s#162]
**Describe the bug**
I am currently experiencing an issue where I request dynamic database credentials from Vault. The init container initially fetches the credentials and correctly stores them. When the main container starts up, it reads the contents of that file and can connect to the database. However, the sidecar refreshes the secret and apparently uses a new lease for obtaining database credentials. The file is therefore overwritten, only the new (unused) credentials are continuously extended and the client loses access after an hour (the credential's TTL).

**To Reproduce**

1. Use the following manifest to deploy Drone
2. After the database credential's TTL, the application loses access to the database

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: default.test
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/ca-cert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        vault.hashicorp.com/agent-requests-cpu: 10m
        vault.hashicorp.com/agent-inject-secret-env-db: postgres/creds/postgres
        vault.hashicorp.com/agent-inject-template-env-db: |
          {{ with secret "postgres/creds/postgres" }}
          export DRONE_DATABASE_DATASOURCE=postgres://{{ .Data.username }}:{{ .Data.password }}@postgres.example.com:5432/postgres
          {{ end }}
    spec:
      serviceAccountName: service-account
      containers:
      - name: server
        image: drone:1.9.0
        command:
        - sh
        - -c
        - source /vault/secrets/env-db && /bin/drone-server
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
```

**Expected behavior**
The sidecar container should use the same token as the init container for obtaining database credentials.

**Environment**
* GKE (v1.17.7-gke.15)
* vault-k8s version: v.1.4.2
* Vault uses TLS via a certificate signed by the Kubernetes CA
