### ISSUE TITLE
Mechanism for injecting vault-ca.crt

### ISSUE THREAD

**Issue by cpick** [hashicorp/vault-k8s#19]
Very excited for this `vault`/k8s integration!

In our setup we have `vault` installed within its own, "vault", namespace.  It has a cluster-readable ConfigMap ("cm/vault-ca") that contains ".data.ca\.crt".  Currently, any Deployements/Jobs that would like to fetch a secret from `vault` GET "cm/vault-ca" from the k8s API Server and then use that to to TLS validation when communicating with `vault`.

With the injector I see that there is a `vault.hashicorp.com/tls-secret` annotation that will mount a Secret containing TLS certs (and that mount point can be referenced by `vault.hashicorp.com/ca-cert`), but since our "vault-ca" ConfigMap isn't a Secret (and, more importantly, is in a different namespace) we can't successfully mount it.  We could try to duplicate "cm/vault-ca"s contents into Secrets in each Namespace, but then we'd have to worry about keeping them in sync and about how to protect them from tampering.

Since we've already installed the injector alongside `vault` in the "vault" namespace and since it's already modifying Pods as they're created, it seems like it would be able to actually insert the correct CA into the `vault-agent` init containers/sidecars (much like it already does with the $VAULT_CONFIG environment variable).

**Comment by jasonodonnell** [comment]
Hi @cpick, I think it could be a nice feature if we allowed setting the CA as an environment variable as part of the injection instead of mounting a secret.  We'll consider doing this in the new year!  For now you'll probably need to duplicate the CA until we support this.

**Comment by eam-cs** [comment]
Any updates on this?

**Comment by joemiller** [comment]
Interested in this feature as well. Might also be able to send a PR for it, time permitting.

@jasonodonnell Do you envision setting the contents of a PEM-encoded CA cert in the agent-injector's deployment.yaml and then injecting that as a file in the vault agent initContainer + sidecar?

perhaps something along the lines of:

```yaml
# agent-injector-deployment.yaml:
...
          args:
            - agent-inject
            - 2>&1
          env:
            - name: AGENT_INJECT_VAULT_CACERT
              value: |
                 -----BEGIN CERTIFICATE-----
                 ...
                 -----END CERTIFICATE-----
```

or perhaps it would be consumed via a file, possibly a ConfigMap or SecretVolume mounted into the agent injector container:

```yaml
# agent-injector-deployment.yaml:
...
          args:
            - agent-inject
            - 2>&1
          env:
            - name: AGENT_INJECT_VAULT_CACERT
              value: /ca-certs/vault.pem
          volumeMounts:
            - mountPath: /ca-certs
              name: vault-ca
        volumes:
          - name: vault-ca
            secret:
              secretName: vault-ca
```

Then in the initContainer and sideCar container:
- if AGENT_INJECT_VAULT_CACERT was set, follow the existing pattern of b64 encoding the `config.json` into the `VAULT_CONFIG` env var:
- b64 encode the cacert into `VAULT_CACERT` env var
- append(?) additional commands to https://github.com/hashicorp/vault-k8s/blob/38c3f0c8d97766167b9b9d5430342655a63acdb3/agent-inject/agent/container_sidecar.go#L18 to decode and write the cacert to `/home/vault.ca.pem`
- set `VAULT_CACERT=/home/vault/ca.pem` environment variable on the init and sidecar container's podSpecs

It would be nice if Vault itself would accept a `VAULT_CACERT` env var that contained the contents of the cert instead of a path to the cert. That would simplify the mechanics here.
