### ISSUE TITLE
Fetching Vault minted PKI certificates

### ISSUE THREAD

**Issue by shank7485** [hashicorp/vault-k8s#21]
Thanks for open sourcing the sidecar!

Currently, looking at the code, this Vault sidecar agent is built to support only fetch of `secrets` from a Vault server and it cannot be used to trigger the generation of a new `pki` certificate (https://www.vaultproject.io/docs/secrets/pki/index.html) and fetch it right? Cause the only place I see certificate generation is self signed certificates in: https://github.com/hashicorp/vault-k8s/blob/master/helper/cert/source_gen.go#L117-L160.

The reason I ask for this is, the use cause is to use the sidecar to ask Vault to generate a new `pki` cert and use that cert with shared volume with other containers in a Pod. That way, short lived`pki` certs feature of Vault is directly supported by this agent and they can be refreshed easily via the sidecar. 

Is this feature supported or is it planning to be developed anytime in the future timelines? Please let me know. Thanks!

**Comment by jasonodonnell** [comment]
I need to test this, however, this template should be possible:

```
vault.hashicorp.com/agent-inject-secret-pki-example: "pki/issue/my-domain-dot-com"
vault.hashicorp.com/agent-inject-template-pki-example: |
    {{ with secret "pki/issue/my-domain-dot-com" "common_name=foo.example.com" }}
    {{ .Data.certificate }}
    {{ end }
```

**Comment by jasonodonnell** [comment]
I confirmed that this worked!  This was possible:

```yams
spec:
  template:
    metadata:
      annotations:
        # AGENT INJECTOR SETTINGS
        vault.hashicorp.com/agent-inject: "true"
        ...
        # TLS SERVER CERTIFICATE
        vault.hashicorp.com/agent-inject-secret-server.cert: "pki/issue/hashicorp-com"
        vault.hashicorp.com/agent-inject-template-server.cert: |
          {{- with secret "pki/issue/hashicorp-com" "common_name=www.hashicorp.com" -}}
          {{ .Data.certificate }}
          {{- end }}
        # TLS SERVER KEY
        vault.hashicorp.com/agent-inject-secret-server.key: "pki/issue/hashicorp-com"
        vault.hashicorp.com/agent-inject-template-server.key: |
          {{- with secret "pki/issue/hashicorp-com" "common_name=www.hashicorp.com" -}}
          {{ .Data.private_key }}
          {{- end }}
        # TLS CA CERTIFICATE
        vault.hashicorp.com/agent-inject-secret-ca.cert: "pki/issue/hashicorp-com"
        vault.hashicorp.com/agent-inject-template-ca.cert: |
          {{- with secret "pki/issue/hashicorp-com" "common_name=www.hashicorp.com" -}}
          {{ .Data.issuing_ca }}
          {{- end }}
        ...
```

**Comment by sgarlick987** [comment]
@jasonodonnell related to this, is it possible to get the pod ip into the vault injector so that we could add ipsans of the pod itself to the cert template? I'm converting some older manifests to use the k8s injector and while most move over fine, the few where I'm using ipsans I'm not sure how to convert as we inject that info as an env var and then use that in the templates right now. 

I can open a different issue if needed, just thought you might know since you were looking into this.

**Comment by ppandiya** [comment]
@jasonodonnell in a helm chart template is not working. throwing a function "secret" not defined error. I looked at a reply on the same issue. tried that as well. its throwing a different error.

**Comment by saurav-k** [comment]
@ppandiya use like this 

spec:
  template:
    metadata:
      annotations:
        # AGENT INJECTOR SETTINGS
        vault.hashicorp.com/agent-inject: "true"
        ...
        # TLS SERVER CERTIFICATE
        vault.hashicorp.com/agent-inject-secret-server.cert: "pki/issue/hashicorp-com"
        vault.hashicorp.com/agent-inject-template-server.cert: |
          {{printf `{{- with secret "pki/issue/hashicorp-com" "common_name=www.hashicorp.com" -}}
          {{ .Data.certificate }}
          {{- end }}` }}
        ...

**Comment by JoostvdB94** [comment]
> I confirmed that this worked! This was possible:
> 
> ```yaml
> spec:
>   template:
>     metadata:
>       annotations:
>         # AGENT INJECTOR SETTINGS
>         vault.hashicorp.com/agent-inject: "true"
>         ...
>         # TLS SERVER CERTIFICATE
>         vault.hashicorp.com/agent-inject-secret-server.cert: "pki/issue/hashicorp-com"
>         vault.hashicorp.com/agent-inject-template-server.cert: |
>           {{- with secret "pki/issue/hashicorp-com" "common_name=www.hashicorp.com" -}}
>           {{ .Data.certificate }}
>           {{- end }}
>         # TLS SERVER KEY
>         vault.hashicorp.com/agent-inject-secret-server.key: "pki/issue/hashicorp-com"
>         vault.hashicorp.com/agent-inject-template-server.key: |
>           {{- with secret "pki/issue/hashicorp-com" "common_name=www.hashicorp.com" -}}
>           {{ .Data.private_key }}
>           {{- end }}
>         # TLS CA CERTIFICATE
>         vault.hashicorp.com/agent-inject-secret-ca.cert: "pki/issue/hashicorp-com"
>         vault.hashicorp.com/agent-inject-template-ca.cert: |
>           {{- with secret "pki/issue/hashicorp-com" "common_name=www.hashicorp.com" -}}
>           {{ .Data.issuing_ca }}
>           {{- end }}
>         ...
> ```

Very cool!
Could this be added to the examples on https://www.vaultproject.io/docs/platform/k8s/injector/examples ?

**Comment by sosoriov** [comment]
It works!

but i was wondering if there is a way to prevent to create a new certificate every time you scale up your application or a pod gets restarted.

**Comment by saurav-k** [comment]
I was also looking for that use case , Is their anyone already working on that .?  @jasonodonnell 

Feature 
--------

Let's say my nginx is requesting cert from vault , and it crashes in between and kubernetes will restart it.
When it restart it creates new certificate , is their a way to reuse existing certificates.

**Comment by sgarlick987** [comment]
You might want to look at https://cert-manager.io/docs/configuration/vault/ which can manage a cert as a k8s secret and mount that in for those use cases.

**Comment by ixe013** [comment]
@saurav-k you must deal with renewal even if you nginx never crashes, because your certificate **will** expire someday. With that in mind:

- Make your certificates very short lived, say from 3 to 7 days max.
- Get a new cert at each startup (after a crash, upgrade or otherwise)
- Old certificates will expire quickly so it is not a real issue

**Comment by vkarev** [comment]
@jasonodonnell @sosoriov Could you share how to setup roles and policies in Vault for sidecar to be authorized to issue certificates?

**Comment by bguedel** [comment]
> I confirmed that this worked! This was possible:
> 
> ```yaml
> spec:
>   template:
>     metadata:
>       annotations:
>         # AGENT INJECTOR SETTINGS
>         vault.hashicorp.com/agent-inject: "true"
>         ...
>         # TLS SERVER CERTIFICATE
>         vault.hashicorp.com/agent-inject-secret-server.cert: "pki/issue/hashicorp-com"
>         vault.hashicorp.com/agent-inject-template-server.cert: |
>           {{- with secret "pki/issue/hashicorp-com" "common_name=www.hashicorp.com" -}}
>           {{ .Data.certificate }}
>           {{- end }}
>         # TLS SERVER KEY
>         vault.hashicorp.com/agent-inject-secret-server.key: "pki/issue/hashicorp-com"
>         vault.hashicorp.com/agent-inject-template-server.key: |
>           {{- with secret "pki/issue/hashicorp-com" "common_name=www.hashicorp.com" -}}
>           {{ .Data.private_key }}
>           {{- end }}
>         # TLS CA CERTIFICATE
>         vault.hashicorp.com/agent-inject-secret-ca.cert: "pki/issue/hashicorp-com"
>         vault.hashicorp.com/agent-inject-template-ca.cert: |
>           {{- with secret "pki/issue/hashicorp-com" "common_name=www.hashicorp.com" -}}
>           {{ .Data.issuing_ca }}
>           {{- end }}
>         ...
> ```

In this example i think 3 certs get created in the backend; is that correct?
So essentially; given this is part of a deployment, 4 instances of an app starting up would lead to 12 certs being generated.

**Comment by avoidik** [comment]
that's right @bguedel I think the third template with the `.Data.issuing_ca` in it can be replace with the call to `pki/cert/ca_chain` endpoint to retrieve `.Data.certificate`, it will be one certificate less

```
{{- with secret "pki/cert/ca_chain" -}}
{{ .Data.certificate }}
{{- end }}
```

the first two templates can be joined together this in way

```
{{- with secret "pki/issue/hashicorp-com" "common_name=www.hashicorp.com" -}}
{{ .Data.certificate }}
{{- end }}
        # TLS SERVER KEY
        vault.hashicorp.com/agent-inject-secret-server.key: "pki/issue/hashicorp-com"
        vault.hashicorp.com/agent-inject-template-server.key: |
          {{- with secret "pki/issue/hashicorp-com" "common_name=www.hashicorp.com" -}}
          {{ .Data.private_key }}
          {{- end }}
```

**Comment by swenson** [comment]
@vkarev The setup required is:

* Do all the steps in https://learn.hashicorp.com/tutorials/vault/kubernetes-sidecar
* Set a policy that allows your role to access `pki/issue/*` (or your more specific path), e.g.,

```
vault policy write internal-app - <<EOF
path "pki/issue/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}
EOF
```

Now you should be able to `kubectl apply -f` a deployment like:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: issues
  labels:
    app: issues
spec:
  selector:
    matchLabels:
      app: issues
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "internal-app"
        # TLS SERVER CERTIFICATE
        vault.hashicorp.com/agent-inject-secret-server.cert: "pki/issue/hashicorp-com"
        vault.hashicorp.com/agent-inject-template-server.cert: |
          {{- with secret "pki/issue/hashicorp-com" "common_name=www.hashicorp.com" -}}
          {{ .Data.certificate }}
          {{- end }}
        # TLS SERVER KEY
        vault.hashicorp.com/agent-inject-secret-server.key: "pki/issue/hashicorp-com"
        vault.hashicorp.com/agent-inject-template-server.key: |
          {{- with secret "pki/issue/hashicorp-com" "common_name=www.hashicorp.com" -}}
          {{ .Data.private_key }}
          {{- end }}
        # TLS CA CERTIFICATE
        vault.hashicorp.com/agent-inject-secret-ca.cert: "pki/issue/hashicorp-com"
        vault.hashicorp.com/agent-inject-template-ca.cert: |
          {{- with secret "pki/issue/hashicorp-com" "common_name=www.hashicorp.com" -}}
          {{ .Data.issuing_ca }}
          {{- end }}

      labels:
        app: issues
    spec:
      serviceAccountName: internal-app
      containers:
        - name: issues
          image: jweissig/app:0.0.1
```

And see the files populated in `/vault/secrets` inside your app container.
