### ISSUE TITLE
Empty string does not disable injected init container CPU requests

### ISSUE THREAD

**Issue by camba1** [hashicorp/vault-k8s#227]
**Describe the bug**
According to the [docs](https://www.vaultproject.io/docs/platform/k8s/injector/annotations#vault-hashicorp-com-agent-requests-cpu), setting an empty string in the `vault.hashicorp.com/agent-requests-cpu` annotation disables the cpu request of the injected init container. However, setting that value to `""` sets the request to the default 500m and setting it to `" " `(space) causes the init container to not get created. 

**To Reproduce**
Deploy an application
Deploy a patch  that includes the annotation:
`vault.hashicorp.com/agent-requests-cpu: ""` 
Wait for the patch to be applied and then check the CPU request
The cpu request is set to 500m

Application deployment:

```yaml
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "myrole"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-requests-cpu: ""
        vault.hashicorp.com/agent-inject-secret-nats.txt: "mypath"
        ...
```

**Expected behavior**
Based on the docs, I expect not to have the cpu request set to 500m which is way to high specially if you have multiple pods that need to be managed in Vault

**Environment**
* Kubernetes version: 
  * Minikube 1.18
  * Kubectl client 1.20.4 , server 1.20.2
* vault-k8s version: 1.6.1 (installed via helm chart)

**Comment by jasonodonnell** [comment]
Hi @camba1, thanks for the bug report! We're taking a look at this internally but as always, PRs welcome!

**Comment by HamzaZo** [comment]
Hi @camba1  I think that the annotation `vault.hashicorp.com/agent-requests-cpu:""` works as expected. Let's take the following example:
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
       limits:
          cpu: 200m
          memory: 128Mi
       requests:
          memory: 100Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

```
In the above example, I didn't set the `requests.cpu`, by running `kubectl apply -f mypod.yaml` kubernetes automatically assigns the CPU request that matches the limit `requests.cpu: 200m` . see [k8s-manage-resources](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits) doc

```
$ kubectl describe po nginx
<omit>
Containers:
  nginx:
    Container ID:   containerd://d3fdd5c5376ad627c945ae45fc5f4fe4d097972eae9cec827159a064025ea186
    Image:          nginx
    Image ID:       docker.io/library/nginx@sha256:75a55d33ecc73c2a242450a9f1cc858499d468f077ea942867e662c247b5e412
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Wed, 14 Apr 2021 17:03:10 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     200m
      memory:  128Mi
    Requests:
      cpu:        200m
      memory:     100Mi
    Environment:  <none>
<omit>

```
