### ISSUE TITLE
Expected webhook response of admission.k8s.io/v1, Kind=AdmissionReview, got /, Kind=;

### ISSUE THREAD

**Issue by ntx-ben** [hashicorp/vault-k8s#257]
**Describe the bug**
I'm following various tutorials to use `vault-k8s` in my Kubernetes cluster, but I keep getting an error when I deploy my workload (i.e., a simple "echo" Deployment) that will be injected with the vault initContainer/sidecar:

`Internal error occurred: failed calling webhook "vault.hashicorp.com": expected webhook response of admission.k8s.io/v1, Kind=AdmissionReview, got /, Kind=;`

I can see in the logs of the vault-agent that it got called and generated the pod patch, however the workload never comes up. In the logs of the apiserver, I can see the message above.

Even if Vault is not even configured (init, unseal, auth/kubernetes, database secrets, policies, roles, etc.), the vault-agent should be injected into the pod, no?

I'm using Vault v1.7.1 and vault-k8s v0.10.0. I tried in both in a k3s cluster, and also in kind, to no avail. Both running k8s v1.20.2.

Could someone tell me what I'm missing? Thanks

**To Reproduce**
I've scripted the whole thing to spin up a kind cluster, deploy Vault and Postgres, configure Vault, then deploy my "echo" service...

"Admin" policy:
```hcl
# Configure the database secrets engine and create roles
path "database/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}

# Mount secrets engines
path "sys/mounts/*" {
  capabilities = [ "create", "read", "update", "delete", "list" ]
}

# Manage the leases
path "sys/leases/+/database/creds/echo-role/*" {
  capabilities = [ "create", "read", "update", "delete", "list", "sudo" ]
}
path "sys/leases/+/database/creds/echo-role" {
  capabilities = [ "create", "read", "update", "delete", "list", "sudo" ]
}

# Write ACL policies
path "sys/policies/acl/*" {
  capabilities = [ "create", "read", "update", "delete", "list" ]
}

# Manage tokens for verification
path "auth/token/create" {
  capabilities = [ "create", "read", "update", "delete", "list", "sudo" ]
}
```

"echo" service policy:
```hcl
path "database/creds/echo-role" {
  capabilities = ["read"]
}
```

Setup Vault:
```sh
# Vault database policies
cat ./config/vault-policy-database-admin.hcl | kubectl --kubeconfig ./kind.yaml --namespace=vault exec -i vault-0 -- vault policy write admin-policy -
cat ./config/vault-policy-database-echo.hcl | kubectl --kubeconfig ./kind.yaml --namespace=vault exec -i vault-0 -- vault policy write echo-policy -

# Kubernetes Auth
kubectl --kubeconfig ./kind.yaml --namespace=vault exec vault-0 -- vault auth enable kubernetes
kubectl --kubeconfig ./kind.yaml --namespace=vault exec vault-0 -- sh -c 'vault write auth/kubernetes/config \
      kubernetes_host="https://$KUBERNETES_PORT_443_TCP_ADDR:443"'
kubectl --kubeconfig ./kind.yaml --namespace=vault exec vault-0 -- vault write auth/kubernetes/role/echo-role \
      bound_service_account_names=echo \
      bound_service_account_namespaces=echo \
      token_policies=echo-policy \
      ttl=20m

# Database secrets
kubectl --kubeconfig ./kind.yaml --namespace=postgres exec timescaledb-0 -- psql -c "CREATE DATABASE echo;"
kubectl --kubeconfig ./kind.yaml --namespace=postgres exec timescaledb-0 -- psql -c "CREATE USER vault WITH ENCRYPTED PASSWORD 'vaultpassword'; GRANT ALL PRIVILEGES ON DATABASE echo TO vault;"
kubectl --kubeconfig ./kind.yaml --namespace=vault exec vault-0 -- vault secrets enable database
kubectl --kubeconfig ./kind.yaml --namespace=vault exec vault-0 -- vault write database/config/echo \
   plugin_name=postgresql-database-plugin \
   connection_url="postgresql://{{username}}:{{password}}@timescaledb.postgres.svc.cluster.local:5432/echo?application_name=echo&sslmode=disable" \
   allowed_roles=echo-role \
   username="vault" \
   password="vaultpassword" \
   verify_connection="false"
kubectl --kubeconfig ./kind.yaml --namespace=vault exec vault-0 -- vault write -force database/rotate-root/echo
kubectl --kubeconfig ./kind.yaml --namespace=vault exec vault-0 -- vault write database/roles/echo-role \
    db_name=echo \
    creation_statements="CREATE ROLE \"{{name}}\" WITH LOGIN ENCRYPTED PASSWORD '{{password}}' VALID UNTIL '{{expiration}}'; GRANT SELECT ON ALL TABLES IN SCHEMA public TO \"{{name}}\";" \
    default_ttl=1h \
    max_ttl=24h
```

My simple "echo" service:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: disabled
    vault-webhook: enabled
  name: echo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: echo
  namespace: echo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: echo
  namespace: echo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: echo
  namespace: echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: echo
  name: echo
  namespace: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: echo
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/log-level: debug
        vault.hashicorp.com/agent-inject-secret-database-url: 'database/creds/echo'
        vault.hashicorp.com/agent-inject-template-database-url: |
          {{- with secret "database/creds/echo" -}}
          postgres://{{ .Data.username }}:{{ .Data.password }}@timescaledb.postgres.svc.cluster.local:5432/echo?application_name=echo
          {{- end }}
        vault.hashicorp.com/role: 'echo-role'
      labels:
        app.kubernetes.io/name: echo
    spec:
      containers:
      - name: echo
        image: k8s.gcr.io/echoserver:1.10
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      serviceAccountName: echo

```

vault-agent logs:
```
{"@level":"info","@message":"Request received","@module":"handler","@timestamp":"2021-05-11T17:27:03.472468Z","Method":"POST","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/mutate","RawPath":"","ForceQuery":false,"RawQuery":"timeout=10s","Fragment":""}}
{"@level":"debug","@message":"checking if should inject agent..","@module":"handler","@timestamp":"2021-05-11T17:27:03.473265Z"}
{"@level":"debug","@message":"checking namespaces..","@module":"handler","@timestamp":"2021-05-11T17:27:03.473303Z"}
{"@level":"debug","@message":"setting default annotations..","@module":"handler","@timestamp":"2021-05-11T17:27:03.473317Z"}
{"@level":"debug","@message":"creating new agent..","@module":"handler","@timestamp":"2021-05-11T17:27:03.473358Z"}
{"@level":"debug","@message":"validating agent configuration..","@module":"handler","@timestamp":"2021-05-11T17:27:03.473465Z"}
{"@level":"debug","@message":"creating patches for the pod..","@module":"handler","@timestamp":"2021-05-11T17:27:03.473486Z"}
```

**Expected behavior**
vault-agent initContainer/sidecar to be injected in the pod

**Environment**
* Kubernetes version: 
  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.): k3s v1.20.2; also tried with kind 0.10.0
  * Other configuration options or runtime services (istio, etc.):
* vault-k8s version: 0.10.0

**Comment by ntx-ben** [comment]
I noticed in the code that it is explicitly using the `v1beta1 `version of the `AdmissionReview `resource...

For anyone stumbling on this issue, I modified the `MutatingWebhookConfiguration` for the vault-agent to only specify the `v1beta1 `for the `admissionReviewVersions` field:

```
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/name: vault-agent
  name: vault-agent-mutating-webhook
webhooks:
- admissionReviewVersions:
  #- v1
  - v1beta1
  clientConfig:
    caBundle: ""
    service:
      name: vault-agent
      namespace: vault
      path: /mutate
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: vault.hashicorp.com
  # namespaceSelector:
  #   matchLabels:
  #     vault-webhook: enabled
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: None
```

Now I can see the workload has been injected with the proper vault-agent containers.
