### ISSUE TITLE
Injector mutating webhook possibly fatal for a cluster

### ISSUE THREAD

**Issue by sttts** [hashicorp/vault-k8s#258]
https://github.com/hashicorp/vault-k8s/blob/master/deploy/injector-mutating-webhook.yaml#L22 misses label selectors to exclude the webhook itself. This can be fatal for a cluster as it will stop creating pods.

**Comment by joeyslalom** [comment]
Was bitten by this one.  I set `injector.failurePolicy=Fail`, then tried to apply the helm chart but got deployment errors:

`Error creating: Internal error occurred: failed calling webhook "vault.hashicorp.com": Post "https://vault-agent-injector-svc.vault.svc:443/mutate?timeout=4s": no endpoints available for service "vault-agent-injector-svc"   FailedCreate`

I resolved this by using `injector objectSelector` as follows:
```
  objectSelector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: NotIn
      values: ["vault-agent-injector"]
```

**Comment by nyetwurk** [comment]
What is the status of this ticket?

I see https://github.com/hashicorp/vault-k8s/blob/286c36fcff05636581cdedcc4b2686da138ca4bc/deploy/injector-mutating-webhook.yaml#L26 has not changed.

**Comment by nyetwurk** [comment]
What is the status of this issue? I see https://github.com/hashicorp/vault-k8s/blob/286c36fcff05636581cdedcc4b2686da138ca4bc/deploy/injector-mutating-webhook.yaml#L26 has not changed.

**Comment by nyetwurk** [comment]
```yaml
    objectSelector:
      matchExpressions:
      - key: app.kubernetes.io/name
        operator: NotIn
        values: ["vault-injector"]
```
LGTM
