### ISSUE TITLE
Admission Webhook Doesn't Use Pod Security Context

### ISSUE THREAD

**Issue by jschwartzy** [hashicorp/vault-k8s#261]
**Describe the bug**
The admission webhook only looks at the container-level securityContext to determine a runAsUser if the `vault.hashicorp.com/agent-run-as-same-user` is set. Ideally, the webhook should be able to use the pod-level securityContext.

**To Reproduce**
1. create a deployment and set the `securityContext` at the pod level.
2. set `vault.hashicorp.com/agent-run-as-same-user` annotation to true
3. Apply the spec
4. Note the error: 
`Error creating: admission webhook "vault.hashicorp.com" denied the request: error creating new agent sidecar: No SecurityContext found for Container 0`
Application deployment:

```yaml
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: 'vault-injector-example'
   namespace: vault
   labels:
     app: 'vault-injector-example'
 spec:
   replicas: 1
   strategy:
     type: 'RollingUpdate'
     rollingUpdate:
       maxSurge: 25%
       maxUnavailable: 0
   selector:
     matchLabels:
       app: 'vault-injector-example'
   template:
     metadata:
       labels:
         app: 'vault-injector-example'
       annotations:
         vault.hashicorp.com/agent-inject: 'true'
         vault.hashicorp.com/agent-run-as-same-user: 'true'
         vault.hashicorp.com/auth-type: 'aws'
         vault.hashicorp.com/auth-path: 'auth/aws'
         vault.hashicorp.com/auth-config-type: 'iam'
     spec:
       containers:
       - name: 'service'
         image: "nginxinc/nginx-unprivileged:1.16.1-alpine"
         imagePullPolicy: 'Always'
         resources:
           requests:
             cpu: 50m
             memory: 64Mi
       securityContext:
         fsGroup: 65534
         runAsNonRoot: true
         runAsUser: 101
       serviceAccountName: 'vault-injector-example'
       restartPolicy: Always
```

**Expected behavior**
The admission webhook should be able to use the pod-level security context if defined.

**Environment**
* Kubernetes version: 
  * AWS EKS 1.16
* vault-k8s version: 0.10.0
