### ISSUE TITLE
Error updating MutatingWebhookConfiguration: etcdserver: request timed out

### ISSUE THREAD

**Issue by thynquest** [hashicorp/vault-k8s#272]
Hello Everyone

**Describe the bug**
I try to integrate my k8s cluster with an external vault by following this [guide](https://learn.hashicorp.com/tutorials/vault/kubernetes-external-vault?in=vault/kubernetes). But when I want to inject values coming from my vault I have the following error
````
2021-07-12T14:52:04.001Z [INFO]  handler.certwatcher: Updated certificate bundle received. Updating certs...
Error updating MutatingWebhookConfiguration: etcdserver: request timed out

````

**To Reproduce**
1. follow this [guide](https://learn.hashicorp.com/tutorials/vault/kubernetes-external-vault?in=vault/kubernetes) mainly  the chapter `Install the Vault Helm chart configured to address an external Vault`
2. Deploy application annotated for vault-agent injection
3. See error (vault injector logs, vault-agent logs, etc.)

Application deployment:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.deployment.name }}
  annotations:
   vault.hashicorp.com/agent-inject: "true"
   vault.hashicorp.com/role: "my-app-role"
   vault.hashicorp.com/agent-inject-secret-foo.txt: "path/bar"
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      serviceAccountName: myapp-sa
      containers:
      - name: {{ .Values.deployment.name }}
        image: "{{ .Values.deployment.container.image }}:{{ .Values.deployment.version }}"
      
        envFrom:
          - configMapRef:
              name:  {{ .Values.configMap.name }}
        resources:
         requests:
           memory: {{ .Values.deployment.container.requests.memory }}
           cpu: {{ .Values.deployment.container.requests.cpu }}
         limits:
           memory: {{ .Values.deployment.container.limits.memory }}
           cpu: {{ .Values.deployment.container.limits.cpu }}
        imagePullPolicy: {{ .Values.deployment.container.imagePullPolicy }}

        ports:
          - containerPort: {{ .Values.deployment.container.ports.containerPort }}   
      imagePullSecrets:
      - name: {{ .Values.deployment.imagePullSecrets.name }}       
```

**Expected behavior**
the vault pod agent injector was suppose to create another pod wich creates the secret entry in the vault volume. I thought the `etcd time out` message was due to a unsufficient resource, then I added more resources but with no success

**Environment**
* Kubernetes version: 
  * kubernetes version 1.18 
  
* vault-k8s version: 0.13.0

**Additional context**
my external vault server runs with tls on port 8200

Thank you for your help
