### ISSUE TITLE
Provide secret path to injector template

### ISSUE THREAD

**Issue by jacobthemyth** [hashicorp/vault-k8s#338]
**Is your feature request related to a problem? Please describe.**

I often would like to use custom injector templates but not have to duplicate the secret path in the template (i.e. `with secret "secrets/foo"`) since that means that the template annotation can't be reused, for example when using kustomize I have to duplicate the template across kustomizations just because the secret path is different. This isn't specific to kustomize, but here's an example of the kind of duplication I mean:

**Current:**
```yaml
# pod.yaml
apiVersion: apps/v1
kind: Pod
metadata:
  name: foo
  annotations:
        vault.hashicorp.com/agent-inject-secret-foo: KUSTOMIZE_ME
        vault.hashicorp.com/agent-inject-template-foo: KUSTOMIZE_ME

# staging/pod-patch.yaml
- op: replace
  path: "/metadata/annotations/vault.hashicorp.com~1agent-inject-secret-foo"
  value: "secrets/staging/foo"
- op: replace
  path: "/metadata/annotations/vault.hashicorp.com~1agent-inject-template-foo"
  value: "{{- with secret \"secrets/staging/foo\" -}}{{ .Data.username }}{{- end }}"

# production/pod-patch.yaml
- op: replace
  path: "/metadata/annotations/vault.hashicorp.com~1agent-inject-secret-foo"
  value: "secrets/production/foo"
- op: replace
  path: "/metadata/annotations/vault.hashicorp.com~1agent-inject-template-foo"
  value: "{{- with secret \"secrets/production/foo\" -}}{{ .Data.username }}{{- end }}"
```
**Desired:**
```yaml
# pod.yaml
apiVersion: apps/v1
kind: Pod
metadata:
  name: foo
  annotations:
        vault.hashicorp.com/agent-inject-secret-foo: KUSTOMIZE_ME
        vault.hashicorp.com/agent-inject-template-foo: "{{- with secret .SecretPath -}}{{ .Data.username }}{{- end }}"

# staging/pod-patch.yaml
- op: replace
  path: "/metadata/annotations/vault.hashicorp.com~1agent-inject-secret-foo"
  value: "secrets/staging/foo"

# production/pod-patch.yaml
- op: replace
  path: "/metadata/annotations/vault.hashicorp.com~1agent-inject-secret-foo"
  value: "secrets/production/foo"
```

**Describe the solution you'd like**
The diff might not be obvious, but what I'd like is having something like `.SecretPath` available in the template, it seems possible since the default template has the secret path available and as far as I know the secret path isn't optional. https://github.com/hashicorp/vault-k8s/blob/86684e65ababe9615ccbd813b42118a68f9bbda7/agent-inject/agent/config.go#L129

**Describe alternatives you've considered**
The alternatives I've considered (and used) are:
- using the default template then using an init container to morph the secret file into the right format
- duplicating the template
- making the app understand the default map template

But all of these are suboptimal in my experience.

I would have made this a PR instead of an issue since I think it'd be simple to add `secret.Path` to the `Template` struct , but I really have no clue about the implications on security, reliability, or maintainability. Plus, for the life of me, I couldn't figure out where the templates are actually rendered in the agent 😬, but it may not make any sense to change the agent template code, and I don't know whether it's a security risk to add the secret path to the JSON that's sent to the agent.

**Comment by sdhull** [comment]
Yes please

**Comment by cvockrodt** [comment]
Since you're using kustomize, is it possible to use variables in the patch?

**Comment by systemist** [comment]
As I mentioned, this isn't specific to kustomize, that was just the example I had closest to hand. Maybe I should have used vanilla k8s in my example, but the problem is that the key path is duplicated, and that is unnecessary.

**Comment by tavlima** [comment]
I'd go further with the desired example. Why can't we have the secret data be in the scope already, without the need for the (mostly) redundant `with secret`? My use case is pretty simple: my secrets are actually JSON objects, with multiple attributes (think `DATABASE` JSON secret, with `username`, `host` and `password` fields). Of course the template should be flexible enough to allow for pulling secrets from multiple paths and doing other fancy transformations, if needed, but why make the closest-to-standard use case harder than it should? 

```yaml
...
metadata:
  annotations:
        vault.hashicorp.com/agent-inject-secret-foo: path/to/foo/secret
        vault.hashicorp.com/agent-inject-template-foo: "{{- .Data.username }}"
...
```
