### ISSUE TITLE
Invalid jwt signature generated by vault-agent-injector

### ISSUE THREAD

**Issue by idkw** [hashicorp/vault-k8s#340]
**Describe the bug**

I tried to follow the tutorial at https://learn.hashicorp.com/tutorials/vault/kubernetes-external-vault?in=vault/kubernetes#start-vault to connect an agent injector on a Google Cloud Kubernetes Engine cluster to a Hashicorp Cloud Platform Vault cluster.

However when the vault-agent-injector gets deployed on kubernetes, its secret contains a JWT with an invalid signature which is not in base64 but contains "-" and "_" characters.

**To Reproduce**

- Create a vault server using Hashicorp Cloud Platform.

- Follow the tutorial at https://learn.hashicorp.com/tutorials/vault/kubernetes-external-vault?in=vault/kubernetes#start-vault, deploy on a kubernetes cluster the vault agent injector using : 

```
helm install vault hashicorp/vault \
    --set "injector.externalVaultAddr=https://external-vault:8200"
```

- Once the vault-agent-injector is started look at its generated secret.
```
# Find the name of the generated pod, looks like "vault-agent-injector-xxxxxxxx-xxxxx"
pod_name=$(kubectl get pod --output=json | jq -r '.items[].metadata | select(.name|startswith("vault-agent-injector")).name')

# Show the jwt
kubectl exec -it "${pod_name}" -- cat /var/run/secrets/kubernetes.io/serviceaccount/token
```

Mine was (not important since this is a test throwaway deployment): 

`
eyJhbGciOiJSUzI1NiIsImtpZCI6ImtxWDV2OGFGeER3SWg4RmlKaTBUY25zX1RXRnJmRFV1TEJIRWp3czVwc0EifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJldmVyeXNlbnMiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoidmF1bHQtYWdlbnQtaW5qZWN0b3ItdG9rZW4tYncyajYiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoidmF1bHQtYWdlbnQtaW5qZWN0b3IiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI1OTU1NzUyMi0yMzljLTRmMGItYjBhNC0xNDBhZWQ0NGY0ZWIiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZXZlcnlzZW5zOnZhdWx0LWFnZW50LWluamVjdG9yIn0.TkEfaP88aZS6-LkQMYUHhHtWsQQjpIIiBvRh79TisR-Tjx50O7L7MohW12-ip_nqeW9SbwFYi7Rm3JIabC5pRV96uvZn2Woqoqf_tK6yXSU1n4OHILXx4W5VUmBfZGUw9SMdP8nLQjN8OO4Ai2tTcj8onIhxckEavk_kWLEKQ6MDjxEboBylR_oMakerekgsm_YhIumZ5xvhsTFFRqt3dq85VcXE1Ge7lrviluT-2xUcrktcBGnQs8P_AC581YWR7dFb3c4_KPPV95mskmgc3SxvIhgklFdLmmyoviji0wsDxe1p6TQdDt6v4wxwVSo-0_2GmGJQqV9hO3qD5DLj
`

As you can see the signature is not base64 encoded because it contains invalid characters such as "-" and "_".

This is the issue I've noticed after digging in for hours because afterwards when I try to inject secrets in an application pod using the agent it also tries to inject a JWT with an invalid signature and thus fails to authenticate to the vault server.

**Expected behavior**
The JWT signature should be base64 encoded and authentication to vault cloud platform server should work

**Environment**
* Kubernetes version: 
  GKE 1.19
* vault-k8s version: 1.9.2

**Additional context**

**Comment by tomhjp** [comment]
I think that JWT you included is in base64url format, which is expected: https://datatracker.ietf.org/doc/html/rfc4648#section-5

> when I try to inject secrets in an application pod using the agent it also tries to inject a JWT with an invalid signature and thus fails to authenticate to the vault server

Please could you include more details of the specific error message you encounter, and which step of the learn tutorial fails?

**Comment by idkw** [comment]
Ok thank you for the explanation, so this may not be the cause of the issue after all.
During the tutorial I get stuck when deploying the application with kubernetes annotations.

I have a secret : 

```
vault kv get kv-secrets/poc-vault/config

========== Secret Path ==========
kv-secrets/data/poc-vault/config

======= Metadata =======
Key                Value
---                -----
created_time       2022-05-03T17:01:58.422630353Z
custom_metadata    <nil>
deletion_time      n/a
destroyed          false
version            1

====== Data ======
Key         Value
---         -----
password    salsa
username    giraffe
```

Then a policy : 
```
vault policy read poc-vault

path "kv-secrets/poc-vault/config" {
  capabilities = ["read"]
}

```

A role : 
```
vault read auth/kubernetes/role/poc-vault

Key                                 Value
---                                 -----
alias_name_source                   serviceaccount_uid
bound_service_account_names         [poc-vault]
bound_service_account_namespaces    [everysens]
policies                            [poc-vault]
token_bound_cidrs                   []
token_explicit_max_ttl              0s
token_max_ttl                       0s
token_no_default_policy             false
token_num_uses                      0
token_period                        0s
token_policies                      [poc-vault]
token_ttl                           24h
token_type                          default
ttl                                 24h

```

An application service account : 
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: poc-vault
```

An application pod : 
```
apiVersion: v1
kind: Pod
metadata:
  name: poc-vault-app
  labels:
    app: poc-vault-app-with-annotations
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'poc-vault'
    vault.hashicorp.com/agent-inject-secret-credentials.txt: 'kv-secrets/poc-vault/config'
spec:
  serviceAccountName: poc-vault
  containers:
    - name: app
      image: burtlo/devwebapp-ruby:k8s
```

But when the application pod is deployed I have this : 
![image](https://user-images.githubusercontent.com/7012331/166684180-0a72fbde-308b-414a-9b7f-039ec1466fb1.png)

![image](https://user-images.githubusercontent.com/7012331/166684115-74b3bcf0-f43b-4bae-ae1a-9f3c87bf1927.png)

Logs for the init container agent : 

![image](https://user-images.githubusercontent.com/7012331/166684229-a3e493f8-03f2-43a0-8d0e-190315e5a06d.png)

Not sue what to do since there the logs doesn't give any hint about what is wrong for the authentication.
Is there a way to have a detail error log ?
I tried to use the variable `AGENT_INJECT_LOG_LEVEL: trace` on the agent injector but there isn't any more useful logs written.

**Comment by idkw** [comment]
I have a single kubernetes cluster so this is not the issue unfortunately.
I have another finding.

Initially I deployed the injector using (with https): 
```
helm install vault hashicorp/vault \
    --set "injector.externalVaultAddr=https://external-vault:8200"
```

After looking at the tutorial, I have replaced it with (http) : 
```
helm install vault hashicorp/vault \
    --set "injector.externalVaultAddr=http://external-vault:8200"
```

No the error is slightly different in the deployed app : 
![image](https://user-images.githubusercontent.com/7012331/166695410-90fa11f2-41f7-4e17-a794-4c55cb52e05b.png)

**Comment by idkw** [comment]
I managed to made it work.
The solution was to start vault agent ingector like this : 

```
helm install vault hashicorp/vault \
    --set "injector.externalVaultAddr=https://xxxxxxxxxxxxxxxxx.aws.hashicorp.cloud:8200"
```

instead of : 
```
kubectl apply -f - <<EOF
---
apiVersion: v1
kind: Service
metadata:
  name: external-vault
  namespace: everysens
spec:
  ports:
  - protocol: TCP
    port: 8200
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-vault
subsets:
  - addresses:
      - ip: 18.170.27.74
    ports:
      - port: 8200
EOF

helm upgrade --install vault hashicorp/vault \
    --set "injector.externalVaultAddr=https://external-vault:8200"

```

Because when using "https://external-vault:8200" it fails the TLS server authentication due to a different domain name in the certificate and the host name.
So we need either to use the specific HCP hostname directly in vault injector config or put a web server in between so do the url rewriting. In my case with a single vault server per kubernetes cluster, it is much simpler to just directly use the HCP domain name.
