### ISSUE TITLE
Add ability to run Vault Agent Sidecar in the namespace compliant with restricted Pod Security Standard

### ISSUE THREAD

**Issue by r0bj** [hashicorp/vault-k8s#377]
**Is your feature request related to a problem? Please describe.**
It's becoming more common to restrict application namespaces with Pod Security Admission (https://kubernetes.io/docs/concepts/security/pod-security-admission/) especially with restricted Pod Security Standard (https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted).
Unfortunately currently `securityContext` in `vault-agent-init` init container is configured in a way that it's not possible to run it in a namespace compliant with restricted Pod Security Standard. It's because there is a missing field `seccompProfile`:
```
  Warning  FailedCreate  22s               replicaset-controller  Error creating: pods "nginx-test-867b89cf7-8jhlj" is forbidden: violates PodSecurity "restricted:latest": seccompProfile (pod or container "vault-agent-init" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

**Describe the solution you'd like**
`securityContext` for `vault-agent-init` currently looks similar to:
```
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 100
```

So we should probably add:
```
      seccompProfile:
        type: RuntimeDefault
```

in result `securityContext` would look like this:
```
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 100
      seccompProfile:
        type: RuntimeDefault
```

This change would allow to run Vault Agent Sidecar in namespace compliant with restricted Pod Security Standard.
