### ISSUE TITLE
Pod ephemeral local storage usage exceeds the total limit of containers 128Mi

### ISSUE THREAD

**Issue by adiii717** [hashicorp/vault-k8s#387]
**Describe the bug**
A vault injector terminated as soon as it was injected into the pod, here is what we are seeing in the event
`Pod ephemeral local storage usage exceeds the total limit of containers 128Mi.` 
We recently upgraded the [vault helm-chart](https://artifacthub.io/packages/helm/hashicorp/vault) version `0.22.0` which come with `hashicorp/vault-k8s:1.0.0` and `hashicorp/vault:1.11.3`. It was working fine with helm-chart version `0.19.0`

**To Reproduce**
1. Deploy application annotated for vault-agent injection
```
              vault.hashicorp.com/agent-init-first: true
              vault.hashicorp.com/agent-inject: true
              vault.hashicorp.com/agent-inject-command-env.sh: chmod +x /vault/secrets/env.sh
              vault.hashicorp.com/agent-inject-secret-env.sh: kv/my-app/production/us-west-2/secrets
              vault.hashicorp.com/agent-inject-status: injected
              vault.hashicorp.com/agent-inject-template-env.sh:
                {{ with secret "kv/my-app/production/us-west-2/secrets"  }}
                #!/bin/bash
                {{ range $k, $v := .Data.data }}
                export {{ $k }}="{{ $v }}"
                {{ end }}
                {{ end }}
              vault.hashicorp.com/auth-path: auth/kubernetes/production/us-west-2
              vault.hashicorp.com/role: role-name
              vault.hashicorp.com/service: https://example.com
```
4. See error (vault injector logs, vault-agent logs, etc.)
The app was crashing with the above annotation (with default ephemeral limit 128Mi), so we have to increase the  limit to fix the service for now
```
              vault.hashicorp.com/agent-limits-ephemeral: 256Mi
```
Application deployment:

```yaml
# Paste your application deployment yaml here.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  labels:
    app.kubernetes.io/instance: my-app
    app.kubernetes.io/name: my-app
  name: my-app
  namespace: my-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/instance: my-app
      app.kubernetes.io/name: my-app
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-command-env.sh: chmod +x /vault/secrets/env.sh
        vault.hashicorp.com/agent-inject-secret-env.sh: kv/my-app/production/us-west-2/my-app
        vault.hashicorp.com/agent-inject-template-env.sh: "{{ with secret \"kv/my-app/production/us-west-2/my-app\"
          \ }} \n#!/bin/bash\n{{ range $k, $v := .Data.data }}\nexport {{ $k }}=\"{{
          $v }}\"\n{{ end }}\n{{ end }} \n"
        vault.hashicorp.com/agent-limits-ephemeral: 256Mi
        vault.hashicorp.com/auth-path: auth/kubernetes/production/us-west-2
        vault.hashicorp.com/role: role-name
        vault.hashicorp.com/service: https://vault.example.com
      labels:
        app.kubernetes.io/instance: my-app
        app.kubernetes.io/name: my-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/instance: my-app
                app.kubernetes.io/name: my-app
            topologyKey: kubernetes.io/hostname
      containers:
      - command:
        - bash
        - -c
        - source /vault/secrets/env.sh  && java $* -jar artifact.jar
        image: registry.gitlab.com/domain/my-app:v1.15.0
        imagePullPolicy: Always
        name: my-app
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /dumps
          name: heap-dumps
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: my-app-gitlab-com
      nodeSelector:
        lifecycle: spot
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: my-app
      serviceAccountName: my-app
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: heap-dumps
```

**Eviction Event:**

<img width="721" alt="image" src="https://user-images.githubusercontent.com/23054298/193803567-c6d2f5e8-b878-4e43-9469-d5cbfd18f4fe.png">

**Expected behaviour**
It should be working with the default limit i.e 128Mi even after the upgrade.

**Environment**
* Kubernetes version: 
  * EKS `{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-18ef993"}` also `{Major:"1", Minor:"22+", GitVersion:"v1.22.13-eks-15b7512"}`
  * linkerd
* vault-k8s version:
```
hashicorp/vault-k8s:1.0.0
```
