### ISSUE TITLE
Vault Agent should re-read on disk certificate automatically

### ISSUE THREAD

**Issue by ArchiFleKs** [hashicorp/vault-k8s#394]
**Describe the bug**

I'm currently using Kubernetes on EKS plugged to an external Vault server which si secured via TLS and also does mTLS verification. For this I'm using a CA Keypair loaded on cert-manager which generate on the fly short lived certificate to be used by Vault agent on the pods that require access to Vault. This solution works without issue except when certificate arrived at expiration.

* Cert Manager renewal is done correctly
* File on disk is change (projected automatically via secret)

But the on disk file do not seem to be re-read by Vault agent. I'm getting these errors on the vault-agent sidecar which are preventing it to refresh the secrets on disk:

```
=4m38.54s
2022-10-19T11:54:49.713Z [INFO]  auth.handler: authenticating
2022-10-19T11:54:49.864Z [ERROR] auth.handler: error authenticating: error="Put \"https://vault.testnet.domain.com/v1/auth/kubernetes/login\": remote error: tls: bad certificate" backoff=4m3.39s
```

Here are the annotations I'm using on the pods:

```
    vault.hashicorp.com/agent-init-first: "true"
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-status: injected
    vault.hashicorp.com/agent-inject-token: "true"
    vault.hashicorp.com/agent-requests-cpu: 10m
    vault.hashicorp.com/agent-requests-mem: 64Mi
    vault.hashicorp.com/ca-cert: /vault/tls/ca.crt
    vault.hashicorp.com/client-cert: /vault/tls/tls.crt
    vault.hashicorp.com/client-key: /vault/tls/tls.key
    vault.hashicorp.com/role: service-keygen
    vault.hashicorp.com/tls-secret: service-keygen-vault-tls
```

And here are the specs from the cert-manager certificates with a duration of 36h with a renewal before 6h:

```
spec:
  commonName: service-keygen.vaas-testnet
  dnsNames:
  - service-keygen.testnet
  duration: 36h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: vault-clusterissuer
  privateKey:
    algorithm: ECDSA
  renewBefore: 6h0m0s
  revisionHistoryLimit: 3
  secretName: eth-keygen-eth-cli-vault-tls
  usages:
  - client auth
```
Everything works well until the certificate renewal.

Is there any way to force the vault agent to re-read the file on disk before making a request instead of reading them only at startup ? Or am I missing something here ?

**Environment**
* Kubernetes version: 1.23
  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.): EKS
  * Other configuration options or runtime services (istio, etc.):
* vault-k8s version: 1.0.0
* Vault server/agent version: 1.11.3

**Additional context**
I believe there are similar issue with Vault SDK Go
