### ISSUE TITLE
Need secrets as key and value pair available in pod environment directly

### ISSUE THREAD

**Issue by arunporwal** [hashicorp/vault-k8s#45]
I am looking for a way to see if we can include all secrets which we got it from vault, in a container as a environment variable rather then using a file which contains key and value pair. 

Is there any way, when i inject a variables from particular path of vault to container i can directly access those variables as key and value without referring to env block of deployment. 

My use case is : 
Current scenario :  I have few micro services which i want to deploy in k8s. All micro services are using many variables which as of now i am supplying in env block as configmap and secrets of my deployment file.  The problem is whenever i want to add or update any variable i need to  update my deployment as well. (either configmap or secrets) : Developer won't have access to those variables.
Requirement : Now i started using vault and created app specific path and policies for all those variables which are needed for micro services to run then using vault-k8s module i am injecting those variables into my container which is pretty awesome but after injecting those values, again i have to refer those key into my deployment as env block because it inject all those variables into a mount file either developer write code to read that file in the start of service or if is there any way to inject all those key and value pair inside file, directly into my pod environment, In this case there is no need to refer keys into env block of my container. so i can update vault anytime and the variable will be available into pod without updating any deployment file.

```apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-secret-test: kv/devops/demo
    vault.hashicorp.com/role: "demo"
spec:
  serviceAccountName: vault-auth
  containers:
  - name: busybox
    image: busybox:1.28
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    env:
         - name: "CONFIG_FILE"
           value: "/kv/devops/demo/test"
``` 

vault path `kv/devops/demo` contains many variables which are now available in my pod as /kv/devops/demo/test mount file. Any possible way that instead of using as file i can directly inject those keys and values in pod env without specifying as env block.

**Comment by jasonodonnell** [comment]
Hi @arunporwal, this is not possible with the injector today, but we are considering having an option that would generate an envfile which your container could source.

**Comment by arunporwal** [comment]
@jasonodonnell : Thanks for the update. **Really appreciated**. 

But how to source that file in container shell before container it start. There are only 2 lifecycle container hook i believe. ( Prestop and Poststop ) both can be used after after container start or stop and there is no hook which say run it before container start. 
Or if we use init container , i think that will also not worked because it will source env in init container shell only. any idea on this ?

**Comment by jasonodonnell** [comment]
I think you would need to do:

```
command: ["/bin/sh", "-ec"]
args: ["source /vault/secrets/test.env"]
```

**Comment by wiltonfelix** [comment]
Hello, have news to this request?

**Comment by OuFinx** [comment]
The same question.
Do you have news?

**Comment by arunporwal** [comment]
@jasonodonnell : Are we going to have this feature in next release ?

**Comment by taffarel-gaivota** [comment]
> Hi @arunporwal, this is not possible with the injector today, but we are considering having an option that would generate an envfile which your container could source.
> 
> One idea could be to use custom templates to create files with a common filename structure:
> 
> ```
>    vault.hashicorp.com/agent-inject-template-db.env: |
>       {{- with secret "database/creds/db-app" -}}
>       #!/bin/bash
>       export USERNAME={{ .Data.username }}
>       export PASSWORD={{ .Data.password }}
>       {{- end }}
>    --- MORE SECRETS HERE ---
>    ...
> ```
> 
> Then your container could source all the files: `source /vault/secrets/*.env`

This use case works well for static secrets. 

In my case I try to use this approach with dynamic secrets but after some time the secret change and the app on that container stop working.

You guys have some suggestions on how to deal with this use case?

**Comment by cpick** [comment]
Related feature request: #14

**Comment by hoantran3108** [comment]
@arunporwal Did you manage to source the env file using the command, args in pod's specification? For me, using the command and args would overwrite the Dockerfile ENTRYPOINT so the container is not able to run as expected.

**Comment by SantiEich** [comment]
Any updates on this feature? +1

**Comment by stewartshea** [comment]
@hoantran3108 Here is the command instruction that I used to do this with an influxdb image. Of course the final command will depend on the configuration of your particular image. 

```
        command: ["/bin/bash", "-c", "source /vault/secrets/influxdb_env && ./entrypoint.sh influxd"]

```

**Comment by pksurferdad** [comment]
@taffarel-gaivota do you have an example of how you sourced variables in your example here https://github.com/hashicorp/vault-k8s/issues/45#issuecomment-604138825?

**Comment by pksurferdad** [comment]
Hi @jasonodonnell , i see how this https://github.com/hashicorp/vault-k8s/issues/45#issuecomment-573767785 is supposed to work now and i followed the instructions [posted here](https://www.vaultproject.io/docs/platform/k8s/injector/examples#environment-variable-example); however, when i exec into the pod, i'm not seeing the template file in the `vault/secrets` volume mount and only see the fetched secret.  there are no errors in the `vault-agent-init` logs.  i also included the pod deployment.  any ideas on why the template file is not being created?

**vault-agent-init logs**
```
2020-10-12T14:28:11.009Z [INFO]  sink.file: creating file sink
2020-10-12T14:28:11.009Z [INFO]  sink.file: file sink configured: path=/home/vault/.vault-token mode=-rw-r-----
2020-10-12T14:28:11.009Z [INFO]  auth.handler: starting auth handler
2020-10-12T14:28:11.009Z [INFO]  auth.handler: authenticating
2020-10-12T14:28:11.009Z [INFO]  template.server: starting template server
2020/10/12 14:28:11.009896 [INFO] (runner) creating new runner (dry: false, once: false)
2020-10-12T14:28:11.010Z [INFO]  sink.server: starting sink server
2020/10/12 14:28:11.010248 [INFO] (runner) creating watcher
2020-10-12T14:28:11.020Z [INFO]  auth.handler: authentication successful, sending token to sinks
2020-10-12T14:28:11.020Z [INFO]  auth.handler: starting renewal process
2020-10-12T14:28:11.020Z [INFO]  sink.file: token written: path=/home/vault/.vault-token
2020-10-12T14:28:11.020Z [INFO]  sink.server: sink server stopped
2020-10-12T14:28:11.020Z [INFO]  sinks finished, exiting
2020-10-12T14:28:11.020Z [INFO]  template.server: template server received new token
2020/10/12 14:28:11.020499 [INFO] (runner) stopping
2020/10/12 14:28:11.020520 [INFO] (runner) creating new runner (dry: false, once: false)
2020/10/12 14:28:11.020633 [INFO] (runner) creating watcher
2020/10/12 14:28:11.020670 [INFO] (runner) starting
2020-10-12T14:28:11.063Z [INFO]  auth.handler: renewed auth token
2020/10/12 14:28:11.132482 [INFO] (runner) rendered "(dynamic)" => "/vault/secrets/poc-secret"
2020/10/12 14:28:11.132515 [INFO] (runner) stopping
2020-10-12T14:28:11.132Z [INFO]  template.server: template server stopped
```

**pod deployment**
`some-secret` is the key of the secret I created in vault.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: vault-agent-demo
spec:
  selector:
    matchLabels:
      app: vault-agent-demo
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "app-user"
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/agent-inject-secret-poc-secret: "secrets/dev/poc-secret"
        vault.hashicorp.com/agent-inject-template-secrets.env: |
          {{- with secret "secrets/dev/poc-secret" -}}
          #!/bin/bash
          export poc_secret={{ .Data.some-secret }}
          {{- end }}
      labels:
        app: vault-agent-demo
    spec:
      serviceAccountName: vault-auth
      containers:
      - name: app
        image: jweissig/app:0.0.1
        args: ["sh", "-c", "source /vault/secrets/secrets.env"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  labels:
    app: app
```

**Comment by jasonodonnell** [comment]
Hi @pksurferdad, your annotations are wrong. To override the default template, your key names need to have the same identifier.

What it should be:

```yaml
vault.hashicorp.com/agent-inject-secret-poc-secret.env: "secrets/dev/poc-secret"
vault.hashicorp.com/agent-inject-template-secrets.env:
```

Here we're saying "for the secret we're identifying as `secret.env`, attach this custom template which creates an environment variable template file.

**Comment by pksurferdad** [comment]
@jasonodonnell that makes sense, but unfortunately, i'm still only seeing the `poc-secret` file in `/vault/secrets` and not the `poc-secret.env` file.  below is the updated deployment.  I assume templating is enabled by default in the `vault-agent-injector`?  I used the latest helm chart to do the install (single/stand-alone k8s AWS EKS cluster). 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: vault-agent-demo
spec:
  selector:
    matchLabels:
      app: vault-agent-demo
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "app-user"
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/agent-inject-secret-poc-secret: "secrets/dev/poc-secret"
        vault.hashicorp.com/agent-inject-template-poc-secret.env: |
          {{- with secret "secrets/dev/poc-secret" -}}
          #!/bin/bash
          export poc_secret={{ .Data.some-secret }}
          {{- end }}
      labels:
        app: vault-agent-demo
    spec:
      serviceAccountName: vault-auth
      containers:
      - name: app
        image: jweissig/app:0.0.1
        args: ["sh", "-c", "source /vault/secrets/poc-secret.env"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  labels:
    app: app
```

**Comment by jasonodonnell** [comment]
@pksurferdad Your annotations are still wrong. They both need to be the same (you're missing `.env`). We use the identifier as the filename but they need to be same.

```yaml
vault.hashicorp.com/agent-inject-secret-poc-secrets.env: "secrets/dev/poc-secret"
vault.hashicorp.com/agent-inject-template-poc-secrets.env:
    {{- with secret "secrets/dev/poc-secret" -}}
    #!/bin/bash
        export poc_secret={{ .Data.some-secret }}
    {{- end }}
```

* vault.hashicorp.com/agent-inject-secret-*poc-secrets.env*
* vault.hashicorp.com/agent-inject-template-*poc-secrets.env*

**Comment by pksurferdad** [comment]
yep, that was it @jasonodonnell.  sorry about that.  i fought a syntax error in the template for a bit (doesn't like `some-secret` for the key and had to change it to `somesecret`).  below is the updated deployment.  now on to figuring out why the `source` command on the `args:` parm is not firing when the container starts up.

**deployment yaml**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: vault-agent-demo
spec:
  selector:
    matchLabels:
      app: vault-agent-demo
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "app-user"
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/agent-inject-secret-poc-secret.env: "secrets/dev/poc-secret"
        vault.hashicorp.com/agent-inject-template-poc-secret.env: |
          {{- with secret "secrets/dev/poc-secret" -}}
            #!/bin/bash
            export poc_secret="{{ .Data.somesecret }}"
          {{- end }}
      labels:
        app: vault-agent-demo
    spec:
      serviceAccountName: vault-auth
      containers:
      - name: app
        image: jweissig/app:0.0.1
        args: ["/bin/sh", "-c", "source /vault/secrets/poc-secret.env"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  labels:
    app: app
```

**Comment by pksurferdad** [comment]
yep, that was it @jasonodonnell.  sorry about that.  i fought a syntax error in the template for a bit (doesn't like `some-secret` for the key and had to change it to `somesecret`).  below is the updated deployment.  now on to figuring out why the `source` command on the `args:` parm is not firing when the container starts up.

**deployment yaml**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: vault-agent-demo
spec:
  selector:
    matchLabels:
      app: vault-agent-demo
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "app-user"
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/agent-inject-secret-poc-secret.env: "secrets/dev/poc-secret"
        vault.hashicorp.com/agent-inject-template-poc-secret.env: |
          {{- with secret "secrets/dev/poc-secret" -}}
            #!/bin/bash
            export poc_secret="{{ .Data.somesecret }}"
          {{- end }}
      labels:
        app: vault-agent-demo
    spec:
      serviceAccountName: vault-auth
      containers:
      - name: app
        image: jweissig/app:0.0.1
        args: ["/bin/sh", "-c", "source /vault/secrets/poc-secret.env"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  labels:
    app: app
```

**Comment by pksurferdad** [comment]
has anyone gotten this to work, to seed the image with env vars from vault?  the pod starts up fine and the secrets are successfully fetched from vault, but are not available on the running pod.  i can exec into the pod and manually run `source /vault/secrets/poc-secret.env` and sets the env var correctly. 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: vault-agent-demo
spec:
  selector:
    matchLabels:
      app: vault-agent-demo
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "app-user"
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/agent-inject-secret-poc-secret.env: "secrets/dev/poc-secret"
        vault.hashicorp.com/agent-inject-template-poc-secret.env: |
          {{- with secret "secrets/dev/poc-secret" -}}
            export poc_secret="{{ .Data.somesecret }}"
          {{- end }}
      labels:
        app: vault-agent-demo
    spec:
      serviceAccountName: vault-auth
      containers:
      - name: app
        image: jweissig/app:0.0.1
        args: ["bin/sh", "-c", "source /vault/secrets/poc-secret.env"]
```
