### ISSUE TITLE
Injector sidecar is working for inject Pod manifest but Deployment manifest doesn't work

### ISSUE THREAD

**Issue by dicky-yuen** [hashicorp/vault-k8s#525]
**Describe the bug**
The injector was suddenly no inject sidecar to the pod since last week. I tested If I apply pod manifest is able to inject sidecar, but deployment manifest cannot inject sidecar.
In production environment, the injector works expected. The configuration is the same.

**To Reproduce**
1. Deploy application annotated for vault-agent injection
2. Deploy Pod test manifest, it works
3. Deploy Deployment test manifest, it doesn't work
4. There is no debug log in vault-injector

Helm values file:
```yaml
injector:
  enabled: "true"
  image:
    repository: "registry.internal/vault/vault-injector"
    tag: "1.3.0"
  agentImage:
    repository: "registry.internal/vault/vault"
    tag: "1.14.1"
  externalVaultAddr: "https://vault-qa.internal:8200"
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 256Mi
      cpu: 250m
  authPath: "auth/rancher-qa"
  metrics:
    enabled: true
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
```

Test deployment manifest:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'data'
        vault.hashicorp.com/tls-secret: 'injector-tls'
        vault.hashicorp.com/client-cert: '/vault/tls/tls.crt'
        vault.hashicorp.com/client-key: '/vault/tls/tls.key'
        vault.hashicorp.com/ca-cert: '/vault/tls/ca.crt'
        vault.hashicorp.com/log-level: 'debug'
        vault.hashicorp.com/agent-inject-secret-config.yaml: 'kv/qa/data/ai1/export'
        vault.hashicorp.com/agent-inject-template-config.yaml: |
          {{ with secret "kv/qa/data/ai1/export" }}
          secrets:
            username: {{ .Data.data.username }}
            password: {{ .Data.data.password }}
          {{ end }}
      labels:
        app: test
    spec:
      serviceAccountName: data
      containers:
      - name: test
        image: registry.internal/test/busybox:1.0.0
        command:
          - sleep
          - "36000"
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
```
Pod test manifest:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'data'
    vault.hashicorp.com/tls-secret: 'injector-tls'
    vault.hashicorp.com/client-cert: '/vault/tls/tls.crt'
    vault.hashicorp.com/client-key: '/vault/tls/tls.key'
    vault.hashicorp.com/ca-cert: '/vault/tls/ca.crt'
    vault.hashicorp.com/agent-inject-secret-config.yaml: 'kv/qa/data/ai1/export'
    vault.hashicorp.com/agent-inject-template-config.yaml: |
      {{ with secret "kv/qa-fra1/data/ai1/export" }}
      secrets:
        username: {{ .Data.data.username }}
        password: {{ .Data.data.password }}
      {{ end }}
  labels:
    app: test
spec:
  serviceAccountName: data
  containers:
  - name: test
    image: registry.internal/test/busybox:1.0.0
    command:
      - sleep
      - "36000"
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi
```

Injector logs
```yaml
2023-09-26T13:44:26.865Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2023-09-26T13:44:26.880Z [DEBUG] handler: checking if should inject agent..
2023-09-26T13:44:26.880Z [DEBUG] handler: checking namespaces..
2023-09-26T13:44:26.880Z [DEBUG] handler: setting default annotations..
2023-09-26T13:44:26.880Z [DEBUG] handler: creating new agent..
2023-09-26T13:44:26.880Z [DEBUG] handler: validating agent configuration..
2023-09-26T13:44:26.880Z [DEBUG] handler: creating patches for the pod..
2023-09-26T13:56:08.961Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2023-09-26T13:56:08.964Z [DEBUG] handler: checking if should inject agent..
2023-09-26T13:56:08.971Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2023-09-26T13:56:08.974Z [DEBUG] handler: checking if should inject agent..
2023-09-26T14:18:14.201Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
```
The Deployment manifest deploy to the cluster, there was no log, and the Pod test manifest showed those logs

**Expected behavior**
Deployment is able to create sidecar

**Environment**
* Kubernetes version: 
  * RKE 1.20
* vault-k8s version: 1.3.0

Additional:
I cannot find any error log related the webhook in apiserver log
