### ISSUE TITLE
Vault agent overwrites kubernetes managedFields

### ISSUE THREAD

**Issue by tymofiiparf** [hashicorp/vault-k8s#528]
**Describe the bug**
After adding vault injection, on pod with vault side car managedFields are missing.
That is causing pod to stuck in running state, even if node is unavailable. Pod is makred with NodeNotReady, but it seems pod with vault sidecar cannot be removed and replaced.
Applications are running in EKS cluster

**To Reproduce**
1. Deploy application annotated for vault-agent injection
2. Drop node, on which pod is running
3. Pod will stuck in Running state almost forever.

Application deployment:

```yaml
        vault.hashicorp.com/agent-init-first: 'true'
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-secret-config-application: 
        vault.hashicorp.com/agent-inject-secret-config-common: 
        vault.hashicorp.com/agent-inject-secret-database-creds-mysql-ro: 
        vault.hashicorp.com/agent-inject-secret-database-creds-mysql-rw: 
        vault.hashicorp.com/agent-inject-secret-rabbitmq-creds-ro: 
        vault.hashicorp.com/agent-inject-secret-rabbitmq-creds-rw: 
        vault.hashicorp.com/agent-revoke-on-shutdown: 'true'
        vault.hashicorp.com/auth-config-region: eu-central-1
        vault.hashicorp.com/auth-config-type: iam
        vault.hashicorp.com/auth-path: auth/aws
        vault.hashicorp.com/auth-type: aws
        vault.hashicorp.com/role: 
```

**Expected behavior**
When pod is injected with vault sidecar, it should contain managedFields, and recreated when Node is not ready

**Environment**
* Kubernetes version: 
  * EKS 1.27.3
  * With istio
* vault-k8s version: hashicorp/vault-k8s:1.3.0 (AGENT_INJECT_VAULT_IMAGE value: hashicorp/vault:1.14.4)
