### ISSUE TITLE
Sidecar agent does not handle manually rotated static database secret

### ISSUE THREAD

**Issue by tylerbrewer2** [hashicorp/vault-k8s#614]
**Describe the bug**
When manually rotating a static database secret, the Vault sidecar agent will not inject the newly created credentials into the pod.

**To Reproduce**
1. Deploy a pod using Vault sidecar to inject database credentials
2. Manually rotate the static database credentials in Vault
3. Pod will continue to use old credentials

Application deployment:

```yaml
vault.hashicorp.com/agent-cache-enable: "true"
vault.hashicorp.com/agent-inject: "true"
vault.hashicorp.com/agent-inject-command-db-creds: |
  ... command to kill container process ...
vault.hashicorp.com/agent-inject-secret-db-creds: database/static-creds/my_db_cred
vault.hashicorp.com/agent-inject-status: injected
vault.hashicorp.com/agent-inject-template-db-creds: |
  ....
vault.hashicorp.com/agent-revoke-on-shutdown: "true"
vault.hashicorp.com/agent-run-as-same-user: "true"
vault.hashicorp.com/role: my_role
vault.hashicorp.com/template-static-secret-render-interval: 1m
```

Other useful info to include: `kubectl describe deployment <app>` and `kubectl describe replicaset <app>` output.

**Expected behavior**
When a credential is manually rotated, I expect the Vault agent to inject the new credentials

**Environment**
* Kubernetes version: 1.28.1
  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.): EKS
* vault-k8s version: 1.1.0
