### ISSUE TITLE
Support Revoking Vault Token on Pod Termination

### ISSUE THREAD

**Issue by lawliet89** [hashicorp/vault-k8s#65]
This is related to https://github.com/hashicorp/vault/issues/6492

Currently, in my (manual) sidecars for Vault Agents, I add a `preStop` hook to revoke the Vault token on pod termination.

```yaml
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - /bin/sleep 10 && /bin/vault token revoke -self
```

This example requires that the Vault token be written to `$HOME/.vault-token` too.
