### ISSUE TITLE
usage of injector in deployments defined in helm chart

### ISSUE THREAD

**Issue by dbeal-wiser** [hashicorp/vault-k8s#68]
when defining an injection template annotation within a deployment defined within a helm chart, the following syntax is required due to golang templates using the same syntax (using one of the examples from the website):

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-example-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-example
  template:
    metadata:
      labels:
        app: app-example
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-db-creds: "database/creds/db-app"
        vault.hashicorp.com/agent-inject-template-db-creds: |
          # for helm we have to escape golang templates to use golang templates for vault
          {{ printf `{{- with secret \"database/creds/db-app\" -}}
          postgres://{{ .Data.username }}:{{ .Data.password }}@postgres:5432/appdb?sslmode=disable
          {{- end }}` }}
        vault.hashicorp.com/role: "db-app"
        vault.hashicorp.com/ca-cert: "/vault/tls/ca.crt"
        vault.hashicorp.com/client-cert: "/vault/tls/client.crt"
        vault.hashicorp.com/client-key: "/vault/tls/client.key"
        vault.hashicorp.com/tls-secret: "vault-tls-client"
    spec:
      containers:
        - name: app
          image: "app:1.0.0"
      serviceAccountName: app-example
```

this syntax does not seem immediately obvious to me, and I understand it would be difficult to change. Could a documentation example/info be added to cover info about using vault inject templates being used inside a helm chart?

**Comment by jasonodonnell** [comment]
Hi @dbeal-wiser, this should work:

```
   annotations:  
        vault.hashicorp.com/agent-inject-template-account: |
          {{` {{- with secret "path/to/secret" -}}
          {{ .Data.test }}
          {{- end }} `}}
```

**Comment by hayderimran7** [comment]
@jasonodonnell  follow-up question, what if `"path/to/secret"` comes from values.yaml 
i want to use something like:
```
   annotations:  
        vault.hashicorp.com/agent-inject-template-account: |
          {{` {{- with secret .Values.vault.path  -}}
          {{ .Data.test }}
          {{- end }} `}}
```

**Comment by hayderimran7** [comment]
got it working 🎆 
```
        vault.hashicorp.com/agent-inject-template-account: |
          {{printf "{{- with secret "}} {{ .Values.vault.path }} {{ ` -}} 
          {{ .Data.test }}
          {{- end }} `}}
```

**Comment by hayderimran7** [comment]
got the ultimate solution for my use case of creating a secret file like:
```
VAL1=secret1
VAL2=secret2
VAL3=secret3
```
to print something like about where the `VALx` are retrieved from helm values.yaml. they are declared as : 
```
external_secrets:
  secrets:
    val1: some value 
     val2: any value
```
# solution 
```
        vault.hashicorp.com/agent-inject-template-creds: |
          {{printf "{{- with secret "}} {{ .Values.vault.path }} {{ ` -}} `}}
          {{- range $key, $value := .Values.external_secrets.secrets }}
          {{ upper $key }}{{ printf "={{.Data."}}{{$key}} {{` }}
          {{- end }} `}}
          {{- end }}
```
