### ISSUE TITLE
hashicorp/vault-k8s:0.1.2 cannot parse the vault.hashicorp.com/auth-path annotation

### ISSUE THREAD

**Issue by smileisak** [hashicorp/vault-k8s#90]
I have noticed an issue related on injecting the init container to login against vault. It looks like the `vault.hashicorp.com/auth-path` is not interpreted correctly and the `vault-agent-init` try to authenticate against the default auth path which is `kubernetes`.

Here is the deployment manifest with the annotations present:

```yaml
apiVersion: extensions/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
        annotations:
          vault.hashicorp.com/agent-inject: "true"
          vault.hashicorp.com/agent-inject-secret-myapp: secret/data/projects/irn-12345/tst-dev/dev/app
          vault.hashicorp.com/auth-path: auth/kubernetes-gke-mut-dev
          vault.hashicorp.com/role: irn-12345-dev
          vault.hashicorp.com/agent-inject-status: update
          vault.hashicorp.com/agent-inject-template-myapp: |
            {{- with secret "secret/data/projects/irn-12345/tst-dev/dev/app" -}}
              postgres://{{ .Data.data.username }}:{{ .Data.data.password }}@postgres:5432/appdb?sslmode=disable
            {{- end }}
        labels:
          app: nginx
    spec:
      serviceAccountName: vault
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
``` 

When applying this configuration the init container stuck with this error

```bash
$ kubectl logs -f -n tst-12345 nginx-deployment-585c548589-b2cmr vault-agent-init
...
URL: PUT http://vault.vault.svc:8200/v1/auth/kubernetes/login
Code: 400. Errors:
* invalid role name "irn-12345-dev"" backoff=1.932763486
```
Using curl i'm able to get a token from the vault server using the jwt of the `vault` service account specified in the configuration by `serviceAccountName`.

```bash
curl -kX POST \
  https://vault.dev.poc.gcp.renault.com/v1/auth/kubernetes-gke-mut-dev/login \
  -H 'Content-Type: application/json' \
  -d '{
        "role": "irn-12345-dev",
        "jwt": "***************"
}' | jq

{
  "request_id": "f9bc5671-1191-e71a-8d41-5136938379d7",
  "lease_id": "",
  "renewable": false,
  "lease_duration": 0,
  "data": null,
  "wrap_info": null,
  "warnings": null,
  "auth": {
    "client_token": "**************",
    "accessor": "**************",
    "policies": [
      "default",
      "irn-12345-dev"
    ],
    "token_policies": [
      "default",
      "irn-12345-dev"
    ],
    "metadata": {
      "role": "irn-12345-dev",
      "service_account_name": "vault",
      "service_account_namespace": "tst-12345",
      "service_account_secret_name": "vault-token-hcgw5",
      "service_account_uid": "66b2a3e9-5c91-11ea-bbaf-4201ac10fe06"
    },
    "lease_duration": 2764800,
    "renewable": true,
    "entity_id": "ffcba332-cc80-ca42-d273-8fedf1918616",
    "token_type": "service",
    "orphan": true
  }
}
```
