### ISSUE TITLE
Authentication per sidecar agent from Kubernetes Secrets

### ISSUE THREAD

**Issue by jaydipdave** [hashicorp/vault-k8s#93]
In large organizations, Kubernetes clusters are very large. Once cluster is used by multiple teams.

Similarly, in Vault LDAP authentication is used along with approle authentication for apps (like Jenkins).

Is there a way to specify a pre-created Kubernetes secret name, as credentials to vault for a specific POD?

Example:

```
vault.hashicorp.com/agent-inject-secret-foo: database/roles/app
vault.hashicorp.com/agent-inject-secret-bar: consul/creds/app
vault.hashicorp.com/approle_secret: nonproduction-staging-app1.secret-management
vault.hashicorp.com/agent-vault-addr: https://somewhat.somewhere.com/
```

```
apiVersion: v1
data:
  auth_method: VVNFUk5BTUVfUEFTU1dPUkQ=
  credentials_password: c2VydmljZS1hY2NvdW50LWFwcDEtcm9sZQ
  credentials_username: U2VydmljZUFjY291bnRBcHAxU2VjcmV0LWlk
kind: Secret
metadata:
  labels:
    managed_by: devops_guys
  name: secret-management
  namespace: nonproduction-staging-app1
type: Opaque
```
